heat_template_version: 2016-10-14

parameters:
    name:
        type: string

    ipv4_enable:
        type: boolean
        default: true

    ipv6_enable:
        type: boolean
        default: false

conditions:
    ipv4_enabled: { get_param: ipv4_enable }
    ipv6_enabled: { get_param: ipv6_enable }

resources:
        #network:
        #    type: OS::Neutron::Net
        #    properties:
        #        name: { get_param: name }

    network:
        type: OS::Neutron::ProviderNet
        properties:
            name: { get_param: name }
            router_external: true
            physical_network: datacentre
            network_type: flat

    ipv4_subnet:
        type: OS::Neutron::Subnet
        properties:
            name: { list_join: ['-', [ 'ipv4', { get_param: name }, 'subnet' ] ] }
            subnetpool: shared-default-subnetpool-v4
            network: { get_resource: network }
        condition: ipv4_enabled

    ipv6_subnet:
        type: OS::Neutron::Subnet
        properties:
            name: { list_join: ['-', [ 'ipv6', { get_param: name }, 'subnet' ] ] }
            ip_version: 6
            subnetpool: shared-default-subnetpool-v6
            network: { get_resource: network }
            ipv6_address_mode: slaac
            ipv6_ra_mode: slaac
        condition: ipv6_enabled

outputs:
    OS::stack_id:
        value: { get_resource: network }
