heat_template_version: 2016-10-14

parameters:
    image:
        type: string
    app_port:
        type: number
        default: 80
    network:
        type: string
    pool:
        type: string
        default: ''
    subnet:
        type: string
        default: ''
    ram:
        type: number
        default: 512

    key_pair:
        type: string
        default: keypair0

conditions:
    lb_enabled:
        not:
            equals:
                - { get_param: pool }
                - ''

resources:
    security_group:
        type: OS::Neutron::SecurityGroup
        properties:
            rules:
                - remote_ip_prefix: 0.0.0.0/0
                  protocol: tcp
                  port_range_min: 22
                  port_range_max: 22
                - remote_ip_prefix: 0.0.0.0/0
                  protocol: tcp
                  port_range_min: { get_param: app_port }
                  port_range_max: { get_param: app_port }
                - remote_ip_prefix: ::/0
                  ethertype: IPv6
                  protocol: tcp
                  port_range_min: { get_param: app_port }
                  port_range_max: { get_param: app_port }
                - remote_ip_prefix: 0.0.0.0/0
                  protocol: udp
                  port_range_min: { get_param: app_port }
                  port_range_max: { get_param: app_port }
                - remote_ip_prefix: ::/0
                  ethertype: IPv6
                  protocol: udp
                  port_range_min: { get_param: app_port }
                  port_range_max: { get_param: app_port }
                - direction: ingress
                  ethertype: IPv4
                  protocol: icmp
                - direction: ingress
                  ethertype: IPv6
                  protocol: ipv6-icmp

    flavor_tiny:
        type: OS::Nova::Flavor
        properties:
            disk: 1
            ram: { get_param: ram }
            vcpus: 1

    server:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor: { get_resource: flavor_tiny }
            key_name: { get_param: key_pair }
            networks:
                - network: { get_param: network }
            security_groups:
                - { get_resource: security_group }
            user_data_format: RAW
            user_data:
                str_replace:
                    template: |
                        #!/bin/sh

                        ip_address=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)

                        curl -k "https://review.opendev.org/gitweb?p=openstack/octavia-tempest-plugin.git;a=blob;f=octavia_tempest_plugin/contrib/test_server/test_server.bin;h=e3cc7ba0c8ad5bc4017a9cd0b5df6b10330a72f5;hb=d6fb54d330c5f38470ef3f9998bbcd714a311f69" > /tmp/test_server
                        chmod +x /tmp/test_server
                        /tmp/test_server -port PORT -id $ip_address

                    params:
                        PORT: { get_param: app_port }

    member:
        type: OS::Octavia::PoolMember
        properties:
            pool: { get_param: pool }
            address: { get_attr: [ server, first_address ] }
            subnet: { get_param: subnet }
            protocol_port: { get_param: app_port }
        condition: lb_enabled

outputs:
    networks:
        description:
        value: { get_attr: [ server, networks ] }
