heat_template_version: 2016-10-14

resources:
    ipv4_pool:
        type: OS::Neutron::SubnetPool
        properties:
            name: shared-default-subnetpool-v4
            prefixes:
                - 172.27.0.0/16
            default_prefixlen: 24
            shared: true

    ipv6_pool:
        type: OS::Neutron::SubnetPool
        properties:
            name: shared-default-subnetpool-v6
            prefixes:
                - fd00:f00::/16
            default_prefixlen: 64
            shared: true
